CREATE TABLE `BELONGSTO` (
    `IID` INT(11) NOT NULL, 
    `GID` INT(11) NOT NULL, 
    PRIMARY KEY (`IID`, `GID`), 
    KEY `GID2_IDX` (`GID`), 
    CONSTRAINT `GID2` FOREIGN KEY (`GID`) REFERENCES `GROUP` (`GID`) ON DELETE CASCADE ON UPDATE CASCADE, 
    CONSTRAINT `IID` FOREIGN KEY (`IID`) REFERENCES `INDIVIDUAL` (`IID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = LATIN1

CREATE TABLE `GROUP` (
    `GID` INT(11) NOT NULL, 
    `CCODE` VARCHAR(45) DEFAULT NULL, 
    `GROUPNAME` VARCHAR(45) DEFAULT NULL,
    `DESCRIPTION` VARCHAR(250) DEFAULT NULL, 
    `TAGS` VARCHAR(45) DEFAULT NULL, 
    `PARENTGROUP` INT(11) DEFAULT NULL, 
    PRIMARY KEY (`GID`),
    CONSTRAINT `CCODE` FOREIGN KEY (`CCODE`) REFERENCES `COMMUNITY` (`CCODE`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = LATIN1

CREATE TABLE `INDIVIDUAL` (
    `IID` INT(11) NOT NULL, 
    `NAME` VARCHAR(45) DEFAULT NULL, 
    `POSITION` VARCHAR(45) DEFAULT NULL, 
    `EMAIL` VARCHAR(45) DEFAULT NULL, 
    `PHONENUMBER` VARCHAR(45) DEFAULT NULL, 
    `SURVEYINFO` VARCHAR(45) DEFAULT NULL, 
    PRIMARY KEY (`IID`)
) ENGINE = INNODB DEFAULT CHARSET = LATIN1

CREATE TABLE `PROJECT` (
    `PID` INT(11) NOT NULL, 
    `PROJECTNAME` VARCHAR(45) DEFAULT NULL, 
    `PROJECTDESCRIPTION` VARCHAR(250) DEFAULT NULL, 
    `PROJECTDIRECTOR` INT(11) DEFAULT NULL, 
    PRIMARY KEY (`PID`), 
    KEY `PROJECTDIRECTOR IS INDIVIDUAL_IDX` (`PROJECTDIRECTOR`), 
    CONSTRAINT `PROJECTDIRECTOR IS INDIVIDUAL` FOREIGN KEY (`PROJECTDIRECTOR`) REFERENCES `INDIVIDUAL` (`IID`) ON DELETE 
    SET 
        NULL ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = LATIN1

CREATE TABLE `TAKESON` (
    `PID` INT(11) NOT NULL, 
    `GID` INT(11) NOT NULL, 
    PRIMARY KEY (`PID`, `GID`), 
    KEY `GID_IDX` (`GID`), 
    CONSTRAINT `GID` FOREIGN KEY (`GID`) REFERENCES `GROUP` (`GID`) ON DELETE CASCADE ON UPDATE CASCADE, 
    CONSTRAINT `PID` FOREIGN KEY (`PID`) REFERENCES `PROJECT` (`PID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = LATIN1

CREATE TABLE `COMMUNITY` (
    `CID` INT(11) NOT NULL, 
    `CCODE` VARCHAR(45) NOT NULL, 
    `NAME` VARCHAR(45) DEFAULT NULL, 
    `ADDRESS` VARCHAR(45) DEFAULT NULL,
    `DESCRIPTION` VARCHAR(250) DEFAULT NULL,
    PRIMARY KEY (`CID`), 
    UNIQUE KEY `CCODE_UNIQUE` (`CCODE`)
) ENGINE = INNODB DEFAULT CHARSET = LATIN1